#!/usr/bin/env bash

what="$1"
where="$2"
who="${3%\!*}"
whoami="$4"
op="c00kiemon5ter"

sayit() {
    printf -- "PRIVMSG %s :%s %s\n" "${where}" "${newho:-${who}}" "$*"
}

if [[ "${what}" =~ ^[[:alpha:]]+\ *\>\ *[[:alpha:]]+ ]]; then
    IFS=\>${IFS} read -r what args  <<< "${what}"
                 read -r newho args <<< "${args}"
elif [[ "${what}" =~ [[:alpha:]]+\ *\>\ *[[:alpha:]]+$ ]]; then
    IFS=\> read -r args newho <<< "${what}"
           read -r what args  <<< "${args}"
           read -r newho      <<< "${newho}"
else
    read -r what args <<< "${what}"
fi

commands=(help list ping test fu forever yuno problem sexy cookies
          pokerface google fortune bewbs gn umad ccc troll random)
[[ "${what}" == random ]] && what="${commands[$((RANDOM%${#commands[@]}))]}"

case "${what}" in
    JOIN)
        newho="ACTION" sayit "la presentato le herpino, ${who}"
        ;;
    PART)
        newho="ACTION" sayit "bye herp derp, ${who}"
        ;;
    list)
        sayit "${commands[*]}"
        ;;
    help)
        sayit "help yourself!"
        ;;
    ping)
        sayit "pong!"
        ;;
    test)
        sayit "tost ready!"
        ;;
    [Ff][Uu])
        sayit "fuuuuuuuuu!"
        ;;
    forever)
        sayit "forever aloooone!"
        ;;
    [yY][uU][nN][oO])
        sayit "Y U NO ${args:-y u no?}"
        ;;
    problem)
        sayit "problem ${args}?"
        ;;
    sexy)
        who="ACTION ${who}" sayit "le sexy time <3 ${args}"
        ;;
    pokerface)
        sayit 'http://i.imgur.com/pKttU.jpg'
        ;;
    cookies)
        [[ "${who}" == "${op}" ]] \
            && sayit "om nom nom nom nom nom nom nom nom nom" \
            || sayit "bake em'"
        ;;
    google)
        # FIXME: report first three results - title & links
        sayit "under construction"
        ;;
    fortune)
        newho="→" who="" sayit "$(/usr/bin/fortune -sea)"
        ;;
    bewbs)
        newho="" who=""
        [[ "${args}" == "moar" ]] && sayit "(  @  )(  @  )" || sayit "( . )( . )"
        ;;
    gn)
        [[ -n "${newho}" ]] && sayit "sleep tight you weak! ${args}" \
                            || who="" sayit "sleep is for the weak."
        ;;
    umad)
        sayit "u mad, bro? ${args}"
        ;;
    ccc)
        newho="" who="" sayit "cococo-co-combobreaker!"
        ;;
    cool)
        who="" sayit "cool.story.bro."
        ;;
    troll)
        sayit "trololololololololololololo"
        ;;
    [[:alpha:]]*)
        newho="" sayit "you don't know what you're talking about, do you?"
        ;;
esac

