#!/usr/bin/env bash

mesg="$1"
chan="$2"
who="${3%\!*}"
declare -r whoami="$4"
declare -r prefix="$5"
declare -r server="$6"
declare -r oper="$USER"
declare -r notes="${prefix}/${server}/messages"

sayit() {
    if [[ -n "${newho:-${who}}" ]]
    then printf -- "PRIVMSG %s :%s: %s\n" "${chan}" "${newho:-${who}}" "${*}"
    else printf -- "PRIVMSG %s :%s\n" "${chan}" "${*}"
    fi
}

[[ "$chan" == "$whoami" ]] && chan="$who"

# nickname   =  ( letter / special ) *8( letter / digit / special / "-" )
# letter     =  %x41-5A / %x61-7A   ; A-Z / a-z
# special    =  %x5B-60 / %x7B-7D   ; "[", "]", "\", "`", "_", "^", "{", "|", "}"
# digit      =  %x30-39             ; 0-9
declare -r nickfmt="([]\\\`_^{|}[:alpha:]])([]\\\`_^{|}[:alnum:]])*"
if [[ "${mesg}" =~ ^[[:alpha:]]+[[:space:]]*\>[[:space:]]*${nickfmt} ]]; then
    IFS=\>${IFS} read -r cmd mesg   <<< "${mesg}"
                 read -r newho mesg <<< "${mesg}"
elif [[ "${mesg}" =~ ^[[:alpha:]].*\>[[:space:]]*${nickfmt}$ ]]; then
    IFS=\> read -r mesg newho <<< "${mesg}"
           read -r cmd mesg   <<< "${mesg}"
           read -r newho      <<< "${newho}"
else
    read -r cmd mesg <<< "${mesg}"
fi

commands=(
    bloat bugs calc cookies isup echo pm
    fortune google help/list links money
    ping/test random pbin news rtfm meme
    sexy slap url yuno r/rhyme dict seen
)

[[ "${cmd,,}" == "random" ]] && cmd="${commands[RANDOM%${#commands[@]}]}"

case "${cmd}" in
    JOIN)
        messages=(
            "la presentato le herpino, ${who}"
            "yo ${who}"
            "kalws ton ${who}"
            "pws ki apo dw ${who}"
            "pou sai re ${who}"
            "pou eisai mwri ${who} ?"
            "lol, ${who} - yolo yolo yolo!"
            "ＷＥＬＣＯＭＥ　ＴＯ　ＴＨＥ　ＦＯＳＳ　ＡＵＥＢ　ＩＲＣ　ＣＨＡＮＮＥＬ"
        )
        if [[ "${who}" == "${oper}" ]]
        then who= newho= sayit "EGERTHEITW!"
        else who= newho= sayit "${messages[RANDOM%${#messages[@]}]}"
        fi

        n="$(cut -d' ' -f1 "${notes}" | grep -c "${who}")"
        (( n > 0 )) && mesg="${n} new messages. use '/msg pancakes !pm' to read them"
        [[ -n "${mesg}" ]] && sayit "${mesg}"
        ;;
    PART)
        messages=(
            "bye herp derp, ${who}"
            "yolo ${who}"
            "tsagia ${who}"
            "antios ${who}"
            "ta leme re ${who}"
            "antio mwri ${who}"
            "gn ${who} - pr0n addict!"
        )
        if [[ "${who}" == "${oper}" ]]
        then who= newho= sayit "TA SEVOI MOY!"
        else who= newho= sayit "${messages[RANDOM%${#messages[@]}]}"
        fi
        ;;
    bloat)
        unset who
        if [[ -n "${mesg}" ]]
        then sayit "${mesg} is bloat!"
        else sayit "bloat is bloat!"
        fi
        ;;
    bugs)
        unset who && sayit "0+2=4 // New Math era! https://bugs.php.net/bug.php?id=61095"
        ;;
    calc)
        mesg="$(bc -l <<< "${mesg}")"
        if [[ -z "${mesg}" ]]
        then sayit "err, ..no"
        else sayit "${mesg}"
        fi
        ;;
    cookies)
        if [[ "${who}" == "${oper}" ]]
        then sayit "om nom nom nom nom nom nom nom nom nom"
        else sayit "bake em' for master ${oper}"
        fi
        ;;
    meme)
        unset who
        messages=(
            "multi ? MUTLI BIKINI ! ΧΩΡΟ-ΧΡΟΝΙΚΗ ΔΙΑΣΠΑΣΗ ΤΩΡΑ ! \
                http://www.arpisoft.gr/patents.html + http://arpisoft/mb.pdf"
            "Sigh. Why my pie die? I so hungry. Now I cry. Life is just a lie. X-(  http://bit.ly/9jwK84"
            "wat? wtf? you haven't read this I guess: http://timecube.com/"
            "ITSATRAP! http://chickencrap.com/media_images/4922.gif"
            "forever aloooone! http://i.imgur.com/xr7Kl.jpg"
            "ULTRAgaaaay http://i.imgur.com/XJ4Aq.png"
            "http://i.imgur.com/SP9gwh.jpg"
            "http://i.imgur.com/EPaUf.jpg"
            "http://i.imgur.com/zV3Wz.gif :3"
            'http://i.imgur.com/pKttU.jpg'
            "trololololololololololololo"
            "u mad, bro? ${mesg}"
            "problem, ${mesg}?"
            "cool.story.bro."
            "failed"
            "believe in Him, trust in Him, be His friend, He will save you. https://lists.launchpad.net/unity-design/msg08084.html"
        )
        sayit "${messages[RANDOM%${#messages[@]}]}"
        ;;
    isitup)
        while read -r site; do
            sayit "$(curl -s "http://isitup.org/${site}" \
                | awk -F"[<>]" '{ for (i=1; i<=NF; i++) if(tolower($i) == "title") { print $(i+1); exit } }')"
        done < <(awk '{ for (i=1; i<=NF; i++)
            if ($i ~ /^http/) print substr($i, index($i, "://") + 3)
            else if ($i ~ /^www/) print $i }' <<< "$mesg")
        ;;
    echo)
        unset who && sayit "$mesg"
        ;;
    fortune)
        unset who newho && while read -r; do sayit "$REPLY"; done < <(fortune -osea)
        ;;
    [Ff][Uu])
        unset who && sayit "fffuuuuuuuuuuuuuuuuuuuuu !!!!!!! >:( ${mesg}"
        ;;
    gn)
        [[ -z "${newho}" ]] && who= sayit "sleep is for the weak." || sayit "sleep tight you weak! ${mesg}"
        ;;
    google)
        unset who
        declar -r api='http://ajax.googleapis.com/ajax/services/search/web?v=1.0'
        curl -s --get --data-urlencode "q=${mesg// /+}" "${api}"                                  \
            | awk -F"[\"\"]" '{ for (i=2; i<=NF; i+=2) if ($i == "unescapedUrl") print $(i+=2) }' \
            | while read -r; do sayit "· $REPLY"; done
        ;;
    news)
        unset who
        declare -r napi='http://www.google.com/ig/api?news'
        declare -r tapi='http://api.bitly.com/v3/shorten?login=pancakesbot&apiKey=R_ac2adceb07f01d8faca52bb77c67293b&longUrl='
        curl -s "${napi}" | awk -F"[<=>\"\"]" '{
        for (f=40; f<=NF; f++)
            if ($f == "title data") a[i++]=$(f+=2)
            else if ($f == "url data") a[i++]=$(f+=2)
        } END { for (i=0; i<=length(a)/2; i+=2) printf("%s %s\n",a[i+1],a[i]) }' | \
            while read -r url title; do
                tiny="$(curl -s "${tapi}${url}&format=txt")"
                sayit "${tiny:-"$url"} - ${title:-"no title found"}"
            done
        ;;
    help|list)
        sayit "help yourself! http://sweet.nodns4.us/"
        sayit "${commands[*]}"
        ;;
    links)
        sayit "all you links are belong to me! https://bitly.com/u/pancakesbot"
        ;;
    money)
        unset who newho
        if [[ "$mesg" =~ ^[[:digit:]]+[[:space:]]+[[:alpha:]]+[[:space:]]+[[:alpha:]]+ ]]; then
            read n f t _ <<< "${mesg}"
            mesg="$(curl -s 'http://www.google.com/ig/calculator?hl=en&q='${n}${f}=?${t} \
                | awk -F"[\"\"]" '$2 { printf("%s is %s\n",$2,$4) }')"
            if [[ -z "${mesg}" ]]
            then sayit "no such unit"
            else sayit "${mesg}"
            fi
        else
            newho= sayit "invalid input"
        fi
        ;;
    pbin)
        unset who && sayit "http://sprunge.us/  http://ideone.com  http://codepad.org/  http://dpaste.com"
        ;;
    dict)
        unset who
        declare -r api='http://glosbe.com/gapi/translate?'
        read -r word _ <<< "$mesg"
        curl -s "${api}from=${from:-"eng"}&dest=${to:-"eng"}&format=json&phrase=${word}&pretty=true"       \
            | awk -F"[\"\"]" -vw="$word" '$2 == "text" { if ($4 != w) print $4; if (++i == 10) { exit } }' \
            | while read -r; do sayit "· $REPLY"; done
        ;;
    r|rhyme)
        while read -r word; do
            word="$(tr -cd "*ςστάέήίόύώΆΈΉΊΌΎΏ[α-ωΑ-Ω][:alnum:]" <<< "$word")"
            r=( $(grep -h "^${word//[*]/[^/]*}$" /usr/share/dict/* /usr/share/hunspell/*.dic ) )
            (( !$? )) && mesg="$(sed "s/${word//[*]/[*]}/${r[RANDOM%${#r[@]}]}/" <<< "$mesg")"
        done < <(awk '{ for (i=1; i<=NF; i++) if ($i ~ /[*]/) print $i }' <<< "${mesg}")
        sayit "${mesg:-"what's the line punk?"}"
        ;;
    rtfm)
        unset who && sayit "be a man, read the man http://xkcd.com/293/"
        ;;
    sexy)
        sayit "le sexy time <3 ${mesg}"
        ;;
    slap)
        sayit "${who} slaps ${newho:-"his cohones"} with a large ${mesg:-"smelly potato donut"}"
        ;;
    ping|test)
        if [[ -z "${newho}" ]]
        then sayit "tost ready!"
        else sayit "ping!"
        fi
        ;;
    url)
        unset who newho
        declare -r api='http://api.bitly.com/v3/shorten?login=pancakesbot&apiKey=R_ac2adceb07f01d8faca52bb77c67293b&format=txt&longUrl='
        while read -r url; do
            # minify link if needed
            (( ${#url} >= 70 )) && tiny="$(curl -s "${api}${url}")"
            # get link title
            title="$(curl -Ls "${url}" | awk -F"[<>]" '{ for (i=1; i<=NF; i++) if (tolower($i) ~ /^title( .+)?/) { print $(i+1); exit }}')"
            # we're done
            [[ -n "${title}" || -n "${tiny}" ]] && sayit "${tiny} -- ${title:-"no title found"}"
        done < <(awk '{ for (i=1; i<=NF; i++) if ($i ~ /^http/) print $i }' <<< "$mesg")
        ;;
    [yY][uU][nN][oO])
        sayit "Y U NO ${mesg:-"y u no?"}"
        ;;
    pm)
        if [[ -z ${newho} && -z ${mesg} ]]
        then # no mesg - read your personal messages
            n=0 && while read -r receiver sender date time mesg
            do [[ "${receiver}" == "${who}" ]] && ((++n)) && sayit "${date} ${time} <${sender}> ${mesg}"
            done < "${notes}"
            if (( n ))
            then printf '%s\n' "g/^${who} /d" "wq" | ed -s "${notes}"
            else sayit "no messages for you but have this http://i.imgur.com/ecvh7.jpg"
            fi
        else # leave a personal message
            [[ -z "${newho}" ]] && sayit "pm who ?" && exit
            [[ -z "${mesg}" ]] && sayit "pm what ?" && exit
            # format: 'receiver sender date time mesg' single space in between fields
            printf -- "%s %s %s %s\n" "${newho}" "${who}" "$(date +"%F %T")" "${mesg}" >> "${notes}" && newho= sayit "noted"
        fi
        ;;
    dbt)
        unset who && sayit "${mesg/%/ }* ba * dum * tss * !! * http://bit.ly/hCDT4P *"
        ;;
    seen)
        [[ "${mesg}" == "${whoami}" ]] && newho= sayit "are you blind or just stupid ?" && exit
        when="$(awk -vn="${mesg}" '$3 == "<"n">" { x = sprintf("%s %s", $1, $2) } END { print x }' "${prefix}/${server}/${chan}/out")"
        unset who && sayit "${mesg} last seen ${when:-"never"}"
        ;;
    *)
        messages=(
            "you don't know what you're talking about, do you?"
            "NO, YOU ${cmd} ${mesg}"
            "apo ta lathi mathainoume, tekna mou"
            "are you a midget, ${who} ?"
            "no faggots here, ${who}"
            "are you tryning to fool me ? are you trying to fool ${whoami} ?"
        )
        unset newho
        if [[ "${who}" == "${oper}" ]]
        then who= sayit "ESFALA ARXONTA!"
        else sayit "${messages[RANDOM%${#messages[@]}]}"
        fi
        ;;
esac

