#!/usr/bin/env bash

what="$1"
where="$2"
who="${3%\!*}"
whoami="$4"
op="$USER"

sayit() {
    printf -- "PRIVMSG %s :%s %s\n" "${where}" "${newho:-${who}}" "$*"
}

if [[ "${what}" =~ ^[[:alnum:]]+\ *\>\ *[[:alnum:]_-]+ ]]; then
    IFS=\>${IFS} read -r what args  <<< "${what}"
                 read -r newho args <<< "${args}"
elif [[ "${what}" =~ [[:alnum:]]+\ *\>\ *[[:alnum:]_-]+$ ]]; then
    IFS=\> read -r args newho <<< "${what}"
           read -r what args  <<< "${args}"
           read -r newho      <<< "${newho}"
else
    read -r what args <<< "${what}"
fi

commands=( alone bewbs bloat bugs calc ccc cookies cool echo f faith fakdat
fap fortune fu gay gn google help i links list money ping poker problem
random rhyme sexy slap temp test trap troll umad url wtf yuno )
[[ "${what}" == random ]] && what="${commands[RANDOM%${#commands[@]}]}"

case "${what}" in
    JOIN)
        newho="ACTION" sayit "la presentato le herpino, ${who}"
        ;;
    PART)
        newho="ACTION" sayit "bye herp derp, ${who}"
        ;;
    alone)
        sayit "forever aloooone! http://i.imgur.com/xr7Kl.jpg"
        ;;
    bewbs)
        newho= who=
        [[ "${args}" == "moar" ]] && sayit "(  @  )(  @  )" || sayit "( . )( . )"
        ;;
    bloat)
        who=
        [[ -n "${args}" ]] && sayit "${args} is bloat!" || sayit "bloat is bloat!"
        ;;
    bugs)
        who= sayit "0+2=4 // New Math era! https://bugs.php.net/bug.php?id=61095"
        ;;
    calc)
        args="$(bc -l <<< "${args}")"
        [[ -z "${args}" ]] && sayit "err, ..no" || sayit "${args}"
        ;;
    ccc)
        newho= who= sayit "cococo-co-combobreaker!"
        ;;
    cookies)
        [[ "${who}" == "${op}" ]] \
            && sayit "om nom nom nom nom nom nom nom nom nom" \
            || sayit "bake em'"
        ;;
    cool)
        who= sayit "cool.story.bro."
        ;;
    echo)
        who= sayit "$args"
        ;;
    f)
        sayit "failed"
        ;;
    faith)
        who= sayit "believe in Him, trust in Him, be His friend, He will save you. https://lists.launchpad.net/unity-design/msg08084.html"
        ;;
    fakdat)
        who= sayit "http://i.imgur.com/SP9gwh.jpg"
        ;;
    fap)
        who= sayit "http://i.imgur.com/EPaUf.jpg"
        ;;
    fortune)
        newho="→" who= sayit "$(/usr/bin/fortune -osea)"
        ;;
    [Ff][Uu])
        sayit "fuuuuuuuuu!"
        ;;
    gay)
        who= sayit "ULTRAgaaaay http://i.imgur.com/XJ4Aq.png"
        ;;
    gn)
        [[ -n "${newho}" ]] && sayit "sleep tight you weak! ${args}" \
                            || who= sayit "sleep is for the weak."
        ;;
    google)
        who= api='http://ajax.googleapis.com/ajax/services/search/web?v=1.0'
        curl -s --get --data-urlencode "q=${args// /+}" ${api}          \
            | sed 's/{\|,/&\n/g'                                        \
            | sed -n '/unescapedUrl/s/"unescapedUrl":"\(.\+\)".*/\1/p'  \
            | cat -n                                                    \
            | while read -r _n _r; do sayit "${_n}. ${_r}"; done
        ;;
    help)
        sayit "help yourself! try !list"
        ;;
    i)
        who= sayit "oh the irony."
        ;;
    links)
        sayit "all you links are belong to me! https://bitly.com/u/pancakesbot"
        ;;
    list)
        sayit "${commands[*]}"
        ;;
    money)
        if [[ "$args" =~ ^[[:digit:]]+[[:space:]]+[[:alpha:]]+[[:space:]]+[[:alpha:]]+ ]]; then
            read n f t _ <<< "${args}"
            args="$(curl -s 'http://www.google.com/ig/calculator?hl=en&q='${n}${f}=?${t} | sed -r 's/.*"(.+)",.*"(.+)",.*".*/\1 → \2/')"
            [[ "${args}" =~ ^\{ ]] && newho= sayit "no such unit" || sayit "${args}"
        else
            newho= sayit "invalid input"
        fi
        ;;
    ping)
        [[ -n "${newho}" ]] && sayit "ping!" || sayit "pong!"
        ;;
    poker)
        sayit 'http://i.imgur.com/pKttU.jpg'
        ;;
    problem)
        who= sayit "problem, ${args}?"
        ;;
    rhyme)
        [[ -z "${args}" ]] && sayit "hit me, aw, I feel no pain, agh" && return
        mapfile -t args < <(curl -s http://uberspot.ath.cx/rhymefinder/ -F "word=${args}" | \
            sed -n -e '/textarea name="results"/s:.*>\(.*\):\1:' -e 's: | :\n:gp')
        (( ${#args[@]} )) && who= sayit "${args[RANDOM%${#args[@]}]}" \
                          || sayit "oh, this hurts bro, I cant rhyme with yo word'"
        ;;
    sexy)
        who="ACTION ${who}" sayit "le sexy time <3 ${args}"
        ;;
    slap)
        [[ -z $newho ]] && newho="his cohones"
        [[ -z $args ]] && args="$who slaps $newho with a large smelly tuna fish" \
                       || args="$who slaps $newho with a large $args"
        who= newho= sayit "$args"
        ;;
    temp)
        read -r args _ <<< "${args}"
        [[ -z "$args" ]] && args="Athens"
        args="$(curl -s "http://www.google.com/ig/api?weather=$args" | iconv -f ISO-8859-15 -t UTF-8 | \
            sed -n 's,.*<city data="\([^/>]*\)"/>.*temp_c data="\([^>]*\)"/>.*<humidity data="\([^>]*\)"/>.*,\1 * \2°C * \3,p')"
        [[ -z "$args" ]] && args="where's that herp ? don't use spaces, use '+'"
        sayit "${args}"
        ;;
    test)
        sayit "tost ready!"
        ;;
    trap)
        who= sayit "ITSATRAP! http://chickencrap.com/media_images/4922.gif"
        ;;
    troll)
        sayit "trololololololololololololo"
        ;;
    umad)
        sayit "u mad, bro? ${args}"
        ;;
    url)
        args="$(sed 's,.*\(http://[^[:space:]]\+\).*,\1,' <<< "$args")"
        tiny="$(curl -s "http://api.bitly.com/v3/shorten?login=pancakesbot&apiKey=R_ac2adceb07f01d8faca52bb77c67293b&longUrl=${args%#*}&format=txt")"
        args="$(sed 's,.*youtube\..*v=\([^&]\+\).*,http://www.youtube.com/embed/\1,' <<< "$args")"  # youtube  links
        args="$(sed 's,.*youtu\.be/\(.\+\),http://www.youtube.com/embed/\1,' <<< "$args")"          # youtu.be links
        args="$(curl -s "$args" | sed -n 's,.*<title>\(.\+\)</title>.*,\1,p')"                      # grab title
        newho= who= sayit ":: $tiny - ${args:-"I guess some funny pic of some sort /b/tards"}"
        ;;
    wtf)
        who= sayit "wat? wtf? you haven't read this I guess: http://timecube.com/"
        ;;
    [yY][uU][nN][oO])
        sayit "Y U NO ${args:-y u no?}"
        ;;
    *)
        #newho= sayit "you don't know what you're talking about, do you?"
        newho= sayit "NO, YOU $what $args"
        ;;
esac

